### ISSUE TITLE
Icons are inconsistent

### ISSUE THREAD

**Issue by uberbryn** [specfm/spec-next#11]
![image](https://user-images.githubusercontent.com/4926824/43369718-85c70504-9327-11e8-8580-2c15dc5d678d.png)

the spectrum logo doesn't fit in with the other logos and there's an icon in the set that would make it more consistent.

![image](https://user-images.githubusercontent.com/4926824/43369731-ae7f8fe8-9327-11e8-87de-85d2f5a9270e.png)

**Comment by brianlovin** [comment]
Thanks! Will replace

**Comment by brianlovin** [comment]
Closed with https://github.com/specfm/spec-next/commit/b8cb44653b11d8dfcbbb9bb6a29a97896940d250
