### ISSUE TITLE
React Podcast URL

### ISSUE THREAD

**Issue by sarahberus** [specfm/spec-next#241]
can we update to - spec.fm/podcasts/reactpodcast

**Comment by SarahMJack** [comment]
i noticed that the episode urls are now getting obfuscated.

is it possible to use SimpleCasts episode url field or episode number?

in all existing episodes we point folks to episode urls like `reactpodcast.com/35`

**Comment by brianlovin** [comment]
Unfortunately we won't be able to do this under the new system, we always need to use the episode ID or token, or otherwise I'd have to write custom API handlers for this one specific podcast route.
