### ISSUE TITLE
Safari doesn't like the shadows around the podcast art

### ISSUE THREAD

**Issue by mknepprath** [specfm/spec-next#42]
Screenshot here: https://twitter.com/mknepprath/status/1034246596345700353?s=21

- I _think_ it's actually the `filter: blur(12px);` 
- I can't replicate the issue locally on the homepage even though it does happen on prod

Again, nice work designing and building this!!

**Comment by brianlovin** [comment]
I think this has been fixed or browsers have caught up, can't repro on my end.

**Comment by mknepprath** [comment]
@brianlovin 👍
