### ISSUE TITLE
Class components to Function components

### ISSUE THREAD

**Issue by abhishekjakhar** [specfm/spec-next#622]
## Description

There are lots of class components in the code, can we convert them to function components?

**Comment by abhishekjakhar** [comment]
@brianlovin I can raise the PR, if that's fine with you? I am new to open source and I am looking for codebases to contribute.

**Comment by brianlovin** [comment]
Hey @abhishekjakhar I appreciate you reaching out! If anything, it's getting close to time to rebuild a lot of this site anyways. I think it's better to hold off on making changes, as I don't want to override your work if we restructure things soon :)

**Comment by abhishekjakhar** [comment]
@brianlovin That's fair enough ,so when you will start recreating it again, can I also contribute?
